version: "3.8"
services:
  webapp:
    build:
      context: .
      target: "develop-stage"
      dockerfile: "./.docker/Dockerfile"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ".:/app:delegated"
      - "/app/node_modules/"
    command: ["npm", "run", "serve"]