version: "3.8"
services:
  webapp-dev:
    build:
      context: .
      target: "develop-stage"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ".:/app:delegated"
      - "/app/node_modules/"
    command: ["npm", "run", "serve"]

  webapp:
    build:
      context: .
      target: "production-stage"
    ports:
      - "127.0.0.1:8080:8080"